---
title: "2018-10-24"
output: html_notebook
---
```{r}
library(googlesheets)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
class(classSurvey)
```

```{r}
names(classSurvey)
colnames(classSurvey)
rownames(classSurvey)
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
as.character(StuDF$name)->StuDF$name
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50),
  stringsAsFactors = F
  )
StuDF 
```

```{r}
names(StuDF) 
colnames(StuDF)
```

```{r}
rownames(StuDF)
```

```{r}
StuDF[1,2]
```

```{r}
StuDF[1,2]
StuDF[,2]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
```

```{r}
StuDF[c(1,2,3),]
StuDF[c(1:3),]
StuDF[c(1:3,5),]
```

```{r}
StuDF[c(1,4),]
StuDF[-c(1,4),]
```

```{r}
StuDF[c(T,F,F,F,F),c(F,T,F)]
StuDF[c(T,F,F,T,F),]
```

```{r}
a<-c(T,T,F,F,T,F,F)
sum(a)
```

```{r}
StuDF[c(T,F,F,F,F),]
StuDF[c(T,F,F,T,F),c(F,T,T,F,F)]
```

```{r}
(StuDF$score >= 80)
(StuDF$name == "小新")
```

```{r}
StuDF
```

```{r}
StuDF[(StuDF$score>=80),c(F,T,F)]
StuDF[c(F,F,F,T,F),c(F,F,T)]
```

```{r}
StuDF[which(StuDF$score>=80),2]
StuDF[which(StuDF$name == "小新"),3]
```

```{r}
which(StuDF$score>=80)
```

```{r}
classSurvey
```

```{r}
(classSurvey$性別 == "男")->aa

(classSurvey$本學期學分數 > 20)->bb

(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)->cc
```

```{r}
classSurvey[(classSurvey$性別=="男"&
 classSurvey$本學期學分數>26),3]
classSurvey[(classSurvey$居住地行政區=="台北市"),3]
classSurvey[(classSurvey$居住地行政區=="新北市"),3]

```

```{r}

```

