---
title: "2018-12-12"
output: html_notebook
---
```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 %>%
  as.factor %>%
  levels -> storageLocations
```

```{r}
libraryData$書籍館藏地 <-
  as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> storageLocations
```

```{r}
i<-2
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```
 
```{r}
# 0
allBorrowCount <- vector("numeric",18)
```
 
```{r}
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```
 
```{r}
names(allBorrowCount) <- storageLocations
```
##不同學院借書量
```{r}
libraryData$學院 %>% as.factor %>% levels ->college

#0
collegeBorrowCount<-vector("numeric",length(college))
for(i in c(1:length(college))){
  #1
  college_i <- college[i]
  #2
  numericalIndexForSubsample <-which(libraryData$學院==college_i)
  collegesubsample_i <-libraryData[numericalIndexForSubsample,]
  #3
  collegeBorrowCount_i <-nrow(collegesubsample_i)
  #4
  collegeBorrowCount[[i]] <-collegeBorrowCount_i
  
}
```

```{r}
libraryData$學號 %>% as.factor %>% levels -> student
libraryData$學院 %>% unique ->student
#0
studentBorrow <- vector("numeric", length(student))
for(i in c(1:length(student))){
#1
  student_i <- student[i]
#2
numericalIndex<- which(libraryData$學號 == student_i)
studentSubsample_i <- libraryData[numericalIndex,]
#3
studentBorrow_i <- nrow(studentSubsample_i)
#4
studentBorrow[[i]] <- studentBorrow_i
}

```

```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result
result
```

```{r}
libraryData %>%
  mutate(
    學系=str_sub(學號,5,6 )
    ##相當於libraryData$學系<-str_sub(libraryData$學號,5,6)
  ) ->libraryData
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) %>%
  ungroup-> result2
result2
```

```{r}
libraryData %>%
  filter(入學年==102)
 ```
 ## 第一次進圖書館
 ```{r}
libraryData %>%
  mutate(
      借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
  ) %>%
  group_by(學號) %>%
  summarise(
    第一次借書=min(借閱時間)
  ) %>%
  ungroup -> result3
result3
```

```{r}
hwGrades <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/hwGrades.csv")
na2Zero<-function(x){
 ifelse(is.na(x),0,x)
}
na2Zero(NA)
hwGrades %>%
  mutate(
   hw1=na2Zero(hw1),
   hw2=na2Zero(hw2),
   Exercise3=na2Zero(Exercise3)
  )->hwGrades
```

```{r}
rowMeans(hwGrades)
```

```{r}
x <- cbind(x1 = 3, x2 = c(4:1, 2:5))
rowSums(x)
colSums(x)
rowMeans(x)
```


