---
title: "2018-10-31"
output: html_notebook
---

```{r}
library(googlesheets)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
library(stringr)
aa<-(str_sub(classSurvey$居住地行政區,1,3))
classSurvey[aa == "台北市",3]
classSurvey[aa=="台北市",c("姓名")]
```

```{r}
classSurvey[aa=="台北市",c("姓名")]->cc
class(cc)
cc$姓名[3]
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
names(gsSurvey)
gsSurvey$links$type
```

```{r}
names(StuDF)
names(StuDF)[2]<-c("姓名")
names(StuDF)
```

```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距)<-c("小個子","小個子","小個子","小個子","小個子","中等個子","中等個子","高個子","高個子")
```

```{r}
student$新身高級距 <- student$身高級距
levels(student$新身高級距)[1:3]<-"(0,160]"
```

##課堂練習
1.1
```{r}
dim(classSurvey)
```
1.2
```{r}
classSurvey$學號->a
as.character(a)->a
str_sub(a,1,4)->a
as.factor(a)->classSurvey$年級
levels(classSurvey$年級)<-c("大四","大三","大二","大一")
```
1.3
```{r}
table(classSurvey$年級)
```
1.4
```{r}
as.factor(classSurvey$性別=="男"&classSurvey$年級=="大二")->b
table(b)
as.factor(classSurvey$性別=="男"&classSurvey$年級=="大三")->c
table(c)
as.factor(classSurvey$性別=="男"&classSurvey$年級=="大四")->d
table(d)
as.factor(classSurvey$年級=="大二"|classSurvey$年級=="大三"|classSurvey$年級=="大四")->e
table(e)
5/14
```
1.6
```{r}
f<-classSurvey$本學期目前已參加之課外活動[classSurvey$年級=="大一"]
str_split_fixed(f,",",n=5)->g
as.character(g)->gg
table(gg)
```


